import {Product} from "./types/Product";

export const Products: Product[] = [
  {
    name: "Nexabook Series 5",
    slug: "nexabook-series5",
    image: "../laptops/Nexa/nexabooks5.jpg",
    category: "Laptops",
    brand: "Nexa",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "Nexabook Series 6",
    slug: "nexabook-series6",
    image: "../laptops/Nexa/nexabooks6.jpg",
    category: "Laptops",
    brand: "Nexa",
    price: 699,
    countInStock: 31,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.1,
    numReviews: 243,
  },

  {
    name: "Nexabook Series 7",
    slug: "nexabook-series7",
    image: "../laptops/Nexa/nexabooks7.jpg",
    category: "Laptops",
    brand: "Nexa",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "Alienwar M15",
    slug: "alienwar-m15",
    image: "../laptops/Alienwar/alienwarm15.jpg",
    category: "Laptops",
    brand: "Alienwar",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "Alienwar M17",
    slug: "alienwar-m17",
    image: "../laptops/Alienwar/alienwarm17.jpg",
    category: "Laptops",
    brand: "Alienwar",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "McBook M1",
    slug: "mcbook-m1",
    image: "../laptops/McBook/mcbookm1.jpg",
    category: "Laptops",
    brand: "McBook",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "McBook M2",
    slug: "mcbook-m2",
    image: "../laptops/McBook/mcbookm2.jpg",
    category: "Laptops",
    brand: "McBook",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "McBook M3",
    slug: "mcbook-m3",
    image: "../laptops/McBook/mcbookm3.jpg",
    category: "Laptops",
    brand: "McBook",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "Razus Blade 14",
    slug: "razus-blade-14",
    image: "../laptops/Razus/razusblade14.jpg",
    category: "Laptops",
    brand: "Razus",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "Razus Blade 15",
    slug: "razus-blade-15",
    image: "../laptops/Razus/razusblade15.jpg",
    category: "Laptops",
    brand: "Razus",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "Razus Blade 16",
    slug: "razus-blade-16",
    image: "../laptops/Razus/razusblade16.jpg",
    category: "Laptops",
    brand: "Razus",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },

  {
    name: "Razus Blade 17",
    slug: "razus-blade-17",
    image: "../laptops/Razus/razusblade17.jpg",
    category: "Laptops",
    brand: "Razus",
    price: 599,
    countInStock: 67,
    description: "Experience seamless performance and effortless multitasking with the cutting-edge 12th Gen Intel Core Processors. Designed to enhance productivity, these processors allow you to breeze through tasks with ease. The revolutionary product is designed with a focus on ease-of-use, performance, and productivity. It is ideal for the entire family, helping them get more out of work, study, or play.",
    rating: 4.6,
    numReviews: 83,
  },
]